version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  orchestrator:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn src.app:app --reload --host 0.0.0.0 --port 8000